#pragma once

enum class Event
{
	GAME_OBJECT_ADDED, GAME_OBJECT_REMOVED, BOMB_EXPLODED, BOMB_DETONATED, GUI_ELEMENT_ADDED,
	GUI_ELEMENT_REMOVED, START_GAME, EXIT_GAME, OPEN_MAIN_MENU, PLAYER_DIED, PLAYER_DAMAGED, OPEN_EDITOR
};
